modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/illegal_stack_fixer/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "illegal_stack_fixer"
version = "${version}"
displayName = "Illegal Stack Fixer"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.illegal_stack_fixer]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.illegal_stack_fixer]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
