modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MrMelon54/illegal_stack_fixer/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "illegal_stack_fixer"
version = "${version}"
displayName = "Illegal Stack Fixer"
authors = "MrMelon54"
description = "Resets stack count to maximum stack size"
logoFile = "/icon.png"

[[dependencies.illegal_stack_fixer]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.illegal_stack_fixer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.illegal_stack_fixer]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
